# For more information: https://laravel.com/docs/sail
version: '3.5'
services:
    laravel.test:
        container_name: "ship-smart_webapp"
        build:
            context: .
            dockerfile: Dockerfile
        image: ship-smart:php8.0-apache-nodejs14
        ports:
            - '${APP_PORT}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - ship-smart_network
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - ship-smart_network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
          retries: 3
          timeout: 5s
networks:
    ship-smart_network:
       name: ship-smart_network
       ipam:
           driver: default
           config:
               - subnet: 172.64.0.0/28
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
